### PR TITLE
Add fastlane metadata for F-Droid

### PR DESCRIPTION
**Pull request by ix5**
Metadata in a fastlane-compatible format is strongly recommended for inclusion in the F-Droid app repository.

Since 4264f20cd, building Rview using the `floss` "flavor" is supported and this gets this app one step closer to inclusion.

Phone screenshots taken on actual phone using SystemUI demo mode, cropped and optimized using `optipng --speed 1`.

`featureGraphic.png` is a copy of `artwork/playstore-banner-1024x500.png`
`icon.png is a copy of artwork/rview-512x512.png`

---

@jruesga it would be great if you could tag a release including this PR soon so that the F-Droid bot can pick it up. You do not need to release the tag of course.

### CODE REVIEW

**Comment by ix5** [comment]
Wow, that was fast! Thanks a lot!
For reference: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7538

**Comment by jruesga** [comment]
Tagged as https://github.com/jruesga/rview/releases/tag/v2.4.1-fastlane

**Comment by ix5** [comment]
Great, thanks!

**Comment by ix5** [comment]
@jruesga seems F-Droid's bot does not pick up `v2.4.1-fastlane` over `v2.4.1`, so a new release that satisfies semver(?) rules is actually required. Please tag `v2.4.2`.

Would be a great opportunity to get rid of the crashing "About" page as well since the last release to the Play Store does not include https://github.com/jruesga/rview/pull/114

**Comment by jruesga** [comment]
ok. thx for the heads up. I will try to publish a release in the following days.

**Comment by jruesga** [comment]
@ix5 v2.4.2 was tagged and released in the PlayStore.

**Comment by ix5** [comment]
Thank you! I hope I can repay your efforts soon with a sweet release in the F-Droid repos ;)

**Pull request merged**
